INSERT INTO tb_category (name) VALUES ('Books', NOW());
INSERT INTO tb_category (name) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name) VALUES ('Computers', NOW());
INSERT INTO tb_category (name) VALUES ('Books', NOW());
INSERT INTO tb_category (name) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name) VALUES ('Computers', NOW());INSERT INTO tb_category (name) VALUES ('Books', NOW());
INSERT INTO tb_category (name) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name) VALUES ('Computers', NOW());INSERT INTO tb_category (name) VALUES ('Books', NOW());
INSERT INTO tb_category (name) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name) VALUES ('Computers', NOW());INSERT INTO tb_category (name) VALUES ('Books', NOW());
INSERT INTO tb_category (name) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name) VALUES ('Computers', NOW());INSERT INTO tb_category (name) VALUES ('Books', NOW());
INSERT INTO tb_category (name) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name) VALUES ('Computers', NOW());INSERT INTO tb_category (name) VALUES ('Books', NOW());
INSERT INTO tb_category (name) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name) VALUES ('Computers', NOW());INSERT INTO tb_category (name) VALUES ('Books', NOW());
INSERT INTO tb_category (name) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name) VALUES ('Computers', NOW());INSERT INTO tb_category (name) VALUES ('Books', NOW());
INSERT INTO tb_category (name) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name) VALUES ('Computers', NOW());INSERT INTO tb_category (name) VALUES ('Books', NOW());
INSERT INTO tb_category (name) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name) VALUES ('Computers', NOW());INSERT INTO tb_category (name) VALUES ('Books', NOW());
INSERT INTO tb_category (name) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name) VALUES ('Computers', NOW());INSERT INTO tb_category (name) VALUES ('Books', NOW());
INSERT INTO tb_category (name) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name) VALUES ('Computers', NOW());INSERT INTO tb_category (name) VALUES ('Books', NOW());
INSERT INTO tb_category (name) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name) VALUES ('Computers', NOW());INSERT INTO tb_category (name) VALUES ('Books', NOW());
INSERT INTO tb_category (name) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name) VALUES ('Computers', NOW());INSERT INTO tb_category (name) VALUES ('Books', NOW());
INSERT INTO tb_category (name) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name) VALUES ('Computers', NOW());INSERT INTO tb_category (name) VALUES ('Books', NOW());
INSERT INTO tb_category (name) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name) VALUES ('Computers', NOW());INSERT INTO tb_category (name) VALUES ('Books', NOW());
INSERT INTO tb_category (name) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name) VALUES ('Computers', NOW());INSERT INTO tb_category (name) VALUES ('Books', NOW());
INSERT INTO tb_category (name) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name) VALUES ('Computers', NOW());INSERT INTO tb_category (name) VALUES ('Books', NOW());
INSERT INTO tb_category (name) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name) VALUES ('Computers', NOW());INSERT INTO tb_category (name) VALUES ('Books', NOW());
INSERT INTO tb_category (name) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name) VALUES ('Computers', NOW());INSERT INTO tb_category (name) VALUES ('Books', NOW());
INSERT INTO tb_category (name) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name) VALUES ('Computers', NOW());INSERT INTO tb_category (name) VALUES ('Books', NOW());
INSERT INTO tb_category (name) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name) VALUES ('Computers', NOW());INSERT INTO tb_category (name) VALUES ('Books', NOW());
INSERT INTO tb_category (name) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name) VALUES ('Computers', NOW());INSERT INTO tb_category (name) VALUES ('Books', NOW());
INSERT INTO tb_category (name) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name) VALUES ('Computers', NOW());